---
driver_plugin: docker

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[mysql::server]
#      - recipe[gerrit::default]
    attributes:
      mysql:
        server_debian_password: "foo"
        server_root_password: "foo"
        server_repl_password: "foo"
