---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-wheezy
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[gerrit::default]
    attributes:
      mysql:
        server_debian_password: "foo"
        server_root_password: "foo"
        server_repl_password: "foo"
