---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-wheezy
  - name: ubuntu-12.04

suites:
  - name: DB-H2
    run_list:
      - recipe[gerrit::default]
    attributes:
      gerrit:
        database:
          type: "H2"
  - name: DB-MYSQL
    run_list:
      - recipe[gerrit::default]
    attributes:
      mysql:
        server_debian_password: "foo"
        server_root_password: "foo"
        server_repl_password: "foo"
